/**
 * Pre-seeded Mock Data for SIH 2026 Presentation & Offline Evaluation
 * Ensures Government Officer Triage, Duplicates, and Assignments work 100%
 * even when local PostgreSQL is not running.
 */

export const DEMO_CHALLENGES: any[] = [
  {
    id: "ch_demo_dam_breach",
    title: "Critical Flash Flood Warning & Subarnarekha River Embankment Erosion",
    description:
      "Severe embankment breach detected near Namkum, Ranchi following heavy upstream discharge from Getalsud Dam. Over 450 households at immediate risk of inundation. Requires immediate UAV aerial drone mapping and geotextile flood barrier deployment.",
    category: "Disaster Management",
    severity: "CRITICAL",
    urgencyScore: 94,
    status: "SUBMITTED",
    latitude: 23.3441,
    longitude: 85.3096,
    address: "Namkum Embankment Road, Subarnarekha River Basin",
    district: "Ranchi",
    state: "Jharkhand",
    pincode: "834010",
    mediaUrls: JSON.stringify([
      "/media/flood-real-1.jpg",
      "/media/flood-real-2.jpg",
    ]),
    audioUrl: "/media/citizen-voice-flood.wav",
    voiceTranscript: "Subarnarekha river embankment erosion active near Namkum bridge. Water entering lowlands, urgent emergency intervention requested.",
    language: "hi",
    isMaster: true,
    duplicateScore: 0.12,
    aiTags: JSON.stringify(["Flood Warning", "Embankment Erosion", "Subarnarekha", "Namkum"]),
    predictedSector: "Disaster Management & Water Resources",
    autoAssignedUniversity: "Birla Institute of Technology, Mesra",
    confidenceScore: 96,
    evidenceStrength: 92,
    priorityScore: 95,
    recommendedDepartment: "Remote Sensing & Civil Engineering",
    slaStatus: "APPROACHING",
    sdgGoals: JSON.stringify(["SDG 11: Sustainable Cities", "SDG 13: Climate Action"]),
    beneficiariesCount: 2400,
    createdAt: new Date(Date.now() - 1000 * 60 * 45), // 45 mins ago
    updatedAt: new Date(Date.now() - 1000 * 60 * 45),
    createdById: "usr_demo_citizen",
    createdBy: {
      id: "usr_demo_citizen",
      name: "Priya Sharma",
      email: "citizen@demo.in",
      role: "CITIZEN",
      district: "Ranchi",
      state: "Jharkhand",
      organization: "Morabadi Residents Welfare Association",
    },
  },
  {
    id: "ch_demo_mining_subsidence",
    title: "Underground Coal Seam Fire & Ground Fissures in Jharia Residential Zone",
    description:
      "Active subsidence and sulfur dioxide venting reported near Bastacolla colliery, Jharia. Ground temperatures exceeding 55°C. Fissures widening along settlement perimeter. Requires thermal infrared satellite monitoring and nitrogen foaming pilot.",
    category: "Mining & Geology",
    severity: "CRITICAL",
    urgencyScore: 91,
    status: "SUBMITTED",
    latitude: 23.7554,
    longitude: 86.4172,
    address: "Bastacolla Colliery Ward 4, Jharia",
    district: "Dhanbad",
    state: "Jharkhand",
    pincode: "828111",
    mediaUrls: JSON.stringify([
      "/media/mining-real-1.jpg",
      "/media/mining-real-2.jpg",
    ]),
    audioUrl: "/media/citizen-voice-mining.wav",
    voiceTranscript: "Active ground fissures and sulfur gas emissions observed near Bastacolla perimeter. Urgent thermal telemetry requested.",
    language: "en",
    isMaster: false,
    duplicateScore: 0.08,
    aiTags: JSON.stringify(["Mine Fire", "Jharia", "Coal Subsidence", "SO2 Gas"]),
    predictedSector: "Mining Safety & Environmental Engineering",
    autoAssignedUniversity: "IIT (ISM) Dhanbad",
    confidenceScore: 94,
    evidenceStrength: 88,
    priorityScore: 92,
    recommendedDepartment: "Mining Engineering & Geophysics",
    slaStatus: "ON_TRACK",
    sdgGoals: JSON.stringify(["SDG 3: Good Health", "SDG 11: Sustainable Cities"]),
    beneficiariesCount: 5200,
    createdAt: new Date(Date.now() - 1000 * 60 * 180), // 3 hours ago
    updatedAt: new Date(Date.now() - 1000 * 60 * 180),
    createdById: "usr_demo_citizen",
    createdBy: {
      id: "usr_demo_citizen",
      name: "Priya Sharma",
      email: "citizen@demo.in",
      role: "CITIZEN",
      district: "Dhanbad",
      state: "Jharkhand",
      organization: "Morabadi Residents Welfare Association",
    },
  },
  {
    id: "ch_demo_arsenic_water",
    title: "Groundwater Arsenic Contamination Exceeding BIS Limits in Sahebganj",
    description:
      "Community tube wells in Rajmahal belt showing arsenic concentrations of 0.08 mg/L against BIS permissible limit of 0.01 mg/L. Keratosis cases observed in local school children. Needs solar-powered iron-arsenic electro-coagulation pilot.",
    category: "Water & Sanitation",
    severity: "HIGH",
    urgencyScore: 82,
    status: "VERIFIED",
    latitude: 25.0484,
    longitude: 87.8427,
    address: "Rajmahal Block, Ganga Alluvial Belt",
    district: "Sahebganj",
    state: "Jharkhand",
    pincode: "816108",
    mediaUrls: JSON.stringify([
      "/media/water-real-1.jpg",
      "/media/water-real-2.jpg",
    ]),
    audioUrl: "/media/citizen-voice-water.wav",
    voiceTranscript: "Deep aquifer tests positive for heavy arsenic concentration. Children showing skin symptoms, water filtration units urgently required.",
    language: "en",
    isMaster: true,
    duplicateScore: 0.05,
    aiTags: JSON.stringify(["Arsenic", "Water Quality", "Sahebganj", "Ganga Basin"]),
    predictedSector: "Public Health Engineering & Chemical Sciences",
    autoAssignedUniversity: "NIT Jamshedpur",
    confidenceScore: 91,
    evidenceStrength: 86,
    priorityScore: 84,
    recommendedDepartment: "Environmental Engineering",
    slaStatus: "ON_TRACK",
    sdgGoals: JSON.stringify(["SDG 6: Clean Water", "SDG 3: Good Health"]),
    beneficiariesCount: 8900,
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 12),
    updatedAt: new Date(Date.now() - 1000 * 60 * 60 * 12),
    createdById: "usr_demo_citizen",
    createdBy: {
      id: "usr_demo_citizen",
      name: "Priya Sharma",
      email: "citizen@demo.in",
      role: "CITIZEN",
      district: "Sahebganj",
      state: "Jharkhand",
    },
  },
  {
    id: "ch_demo_duplicate_flood",
    title: "Subarnarekha River Bank Overflowing Near Namkum Lowland",
    description:
      "Namkum bridge side water entering agricultural fields. High silt accumulation and bank erosion observed since 3 PM today.",
    category: "Disaster Management",
    severity: "HIGH",
    urgencyScore: 88,
    status: "SUBMITTED",
    latitude: 23.3455,
    longitude: 85.3112,
    address: "Namkum Bridge Lowland, Ranchi",
    district: "Ranchi",
    state: "Jharkhand",
    pincode: "834010",
    mediaUrls: JSON.stringify([
      "/media/flood-real-1.jpg",
      "/media/flood-real-2.jpg",
    ]),
    audioUrl: "/media/citizen-voice-flood.wav",
    voiceTranscript: "Agricultural fields flooded near lowlands of Namkum. Embankment sandbagging required immediately.",
    language: "en",
    isMaster: false,
    masterChallengeId: "ch_demo_dam_breach",
    duplicateScore: 0.89,
    duplicateProbability: 89,
    aiTags: JSON.stringify(["Flood", "Namkum", "Subarnarekha"]),
    predictedSector: "Disaster Management",
    confidenceScore: 89,
    evidenceStrength: 80,
    priorityScore: 85,
    slaStatus: "ON_TRACK",
    createdAt: new Date(Date.now() - 1000 * 60 * 30),
    updatedAt: new Date(Date.now() - 1000 * 60 * 30),
    createdById: "usr_demo_citizen",
    createdBy: {
      id: "usr_demo_citizen",
      name: "Priya Sharma",
      email: "citizen@demo.in",
      role: "CITIZEN",
      district: "Ranchi",
      state: "Jharkhand",
    },
  },
];

export const DEMO_AUDIT_LOGS: any[] = [
  {
    id: "log_demo_1",
    action: "STATUTORY_VERIFICATION",
    entityType: "Challenge",
    entityId: "ch_demo_arsenic_water",
    actorId: "usr_demo_admin",
    actorName: "Sri Rajesh Kumar Sinha, IAS",
    details: JSON.stringify({
      verdict: "VERIFIED",
      priorityScore: 84,
      department: "Drinking Water & Sanitation Dept, Govt of Jharkhand",
      notifiedParties: ["NIT Jamshedpur Water Cell", "Sahebganj DC Office"],
    }),
    createdAt: new Date(Date.now() - 1000 * 60 * 120),
    user: {
      name: "Sri Rajesh Kumar Sinha, IAS",
      email: "admin@demo.in",
    },
  },
  {
    id: "log_demo_2",
    action: "UNIVERSITY_RESEARCH_ALLOCATION",
    entityType: "Challenge",
    entityId: "ch_demo_arsenic_water",
    actorId: "usr_demo_admin",
    actorName: "Sri Rajesh Kumar Sinha, IAS",
    details: JSON.stringify({
      university: "NIT Jamshedpur",
      department: "Civil & Environmental Engineering",
      grantScope: "Pilot Deployment Stage-Gate 1",
    }),
    createdAt: new Date(Date.now() - 1000 * 60 * 110),
    user: {
      name: "Sri Rajesh Kumar Sinha, IAS",
      email: "admin@demo.in",
    },
  },
  {
    id: "log_demo_3",
    action: "CSR_GRANT_ENDORSEMENT",
    entityType: "Solution",
    entityId: "sol_demo_nano_filter",
    actorId: "usr_demo_admin",
    actorName: "Sri Rajesh Kumar Sinha, IAS",
    details: JSON.stringify({
      sponsor: "Tata Steel CSR Foundation",
      amountPledged: 2500000,
      section135Compliant: true,
    }),
    createdAt: new Date(Date.now() - 1000 * 60 * 60),
    user: {
      name: "Sri Rajesh Kumar Sinha, IAS",
      email: "admin@demo.in",
    },
  },
  {
    id: "log_demo_4",
    action: "NLP_DECONFLICTION_MERGE",
    entityType: "Challenge",
    entityId: "ch_demo_duplicate_flood",
    actorId: "usr_demo_admin",
    actorName: "Sri Rajesh Kumar Sinha, IAS",
    details: JSON.stringify({
      masterChallengeId: "ch_demo_dam_breach",
      similarityScore: 0.89,
      reason: "Spatial coordinate overlap < 400m and TF-IDF topic concordance on Namkum flood.",
    }),
    createdAt: new Date(Date.now() - 1000 * 60 * 15),
    user: {
      name: "Sri Rajesh Kumar Sinha, IAS",
      email: "admin@demo.in",
    },
  },
];

export const DEMO_UNIVERSITIES: any[] = [
  {
    id: "univ_bit_mesra",
    name: "Birla Institute of Technology, Mesra",
    code: "BIT-MESRA",
    state: "Jharkhand",
    district: "Ranchi",
    departments: JSON.stringify([
      "Remote Sensing & Geoinformatics",
      "Civil & Environmental Engineering",
      "Computer Science & AI",
      "Space Engineering",
    ]),
    expertiseTags: JSON.stringify([
      "UAV Drone Surveillance",
      "GIS Flood Modeling",
      "Early Warning Systems",
      "Disaster Robotics",
    ]),
    nodalOfficerName: "Dr. Aarav Mehta",
    nodalOfficerEmail: "solver@demo.in",
    logoUrl: null,
  },
  {
    id: "univ_iit_ism",
    name: "Indian Institute of Technology (ISM) Dhanbad",
    code: "IIT-ISM",
    state: "Jharkhand",
    district: "Dhanbad",
    departments: JSON.stringify([
      "Mining Engineering",
      "Applied Geophysics",
      "Environmental Science",
      "Petroleum Engineering",
    ]),
    expertiseTags: JSON.stringify([
      "Mine Fire Mitigation",
      "Ground Subsidence Monitoring",
      "Coal Seam Inundation",
      "Geotechnical Sensors",
    ]),
    nodalOfficerName: "Prof. S. K. Roy",
    nodalOfficerEmail: "mining.lead@iitism.ac.in",
    logoUrl: null,
  },
  {
    id: "univ_nit_jsr",
    name: "National Institute of Technology, Jamshedpur",
    code: "NIT-JSR",
    state: "Jharkhand",
    district: "East Singhbhum",
    departments: JSON.stringify([
      "Civil Engineering",
      "Chemical Engineering",
      "Metallurgical & Materials Engineering",
    ]),
    expertiseTags: JSON.stringify([
      "Water Treatment Technologies",
      "Arsenic/Fluoride Filtration",
      "Structural Health Monitoring",
    ]),
    nodalOfficerName: "Dr. Ananya Banerjee",
    nodalOfficerEmail: "env.nitjsr@gov.in",
    logoUrl: null,
  },
];

export const DEMO_DUPLICATE_MERGES: any[] = [
  {
    id: "merge_demo_1",
    masterChallengeId: "ch_demo_dam_breach",
    duplicateChallengeId: "ch_demo_duplicate_flood",
    similarityScore: 0.89,
    reason: "Spatial coordinate overlap < 400m and TF-IDF topic concordance on Namkum flood.",
    mergedById: "usr_demo_admin",
    mergedAt: new Date(Date.now() - 1000 * 60 * 20),
  },
];
